BINTEST_SRCDIR = ${WOLF_TESTDIR}/bintest
UNITTEST_SRCDIR = ${WOLF_TESTDIR}/unittest

include ${BINTEST_SRCDIR}/Makefile ${UNITTEST_SRCDIR}/Makefile

test: ${BINTEST} ${UNITTEST}

test_clean: bintest_clean unittest_clean